version: "3.8"

services: 
  payment:
    image: chuenkaiong/paymentms:1.0
    restart: always
    ports:
      - "5000:80"
    environment:
      - dbURL=sqlite:///./payment_ms.db
      - .env
      # ask chok for this file 