// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh-UJhOh8G14-J5s56OLcRNHPR63lZ5cI',
    appId: '1:60016300716:web:a957274a2fbc1193638509',
    messagingSenderId: '60016300716',
    projectId: 'gobbler-ebd9b',
    authDomain: 'gobbler-ebd9b.firebaseapp.com',
    storageBucket: 'gobbler-ebd9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYhJ2b_sR9p1r3APpJzKdgRX0OQ12DlRg',
    appId: '1:60016300716:android:d414cb2118b01912638509',
    messagingSenderId: '60016300716',
    projectId: 'gobbler-ebd9b',
    storageBucket: 'gobbler-ebd9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8lvUPFdduUpHQXgukEtUc6Ygyhwwqz2E',
    appId: '1:60016300716:ios:cbf5e08dc4143cbe638509',
    messagingSenderId: '60016300716',
    projectId: 'gobbler-ebd9b',
    storageBucket: 'gobbler-ebd9b.appspot.com',
    iosClientId: '60016300716-sn609n6rv8a74f6c3m1f3duo359b9jf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8lvUPFdduUpHQXgukEtUc6Ygyhwwqz2E',
    appId: '1:60016300716:ios:cbf5e08dc4143cbe638509',
    messagingSenderId: '60016300716',
    projectId: 'gobbler-ebd9b',
    storageBucket: 'gobbler-ebd9b.appspot.com',
    iosClientId: '60016300716-sn609n6rv8a74f6c3m1f3duo359b9jf0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );
}
